// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9RU6QuZSdRtXz37jXno7WvETIKmVkd2s',
    appId: '1:637483731243:web:5f2ab4dc2599d20c969d6e',
    messagingSenderId: '637483731243',
    projectId: 'ogrenci-firebase',
    authDomain: 'ogrenci-firebase.firebaseapp.com',
    storageBucket: 'ogrenci-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADJZycdvpC3RdarbwnGLktFGQyLuXD8nw',
    appId: '1:637483731243:android:bdec840aa2092a8a969d6e',
    messagingSenderId: '637483731243',
    projectId: 'ogrenci-firebase',
    storageBucket: 'ogrenci-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqvL6-TpqLz2QTuLv0L5jKrAWe9kAw76k',
    appId: '1:637483731243:ios:56bd2951f83c2ee1969d6e',
    messagingSenderId: '637483731243',
    projectId: 'ogrenci-firebase',
    storageBucket: 'ogrenci-firebase.firebasestorage.app',
    iosBundleId: 'com.example.ogrenciTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqvL6-TpqLz2QTuLv0L5jKrAWe9kAw76k',
    appId: '1:637483731243:ios:56bd2951f83c2ee1969d6e',
    messagingSenderId: '637483731243',
    projectId: 'ogrenci-firebase',
    storageBucket: 'ogrenci-firebase.firebasestorage.app',
    iosBundleId: 'com.example.ogrenciTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9RU6QuZSdRtXz37jXno7WvETIKmVkd2s',
    appId: '1:637483731243:web:62695b21cd06303f969d6e',
    messagingSenderId: '637483731243',
    projectId: 'ogrenci-firebase',
    authDomain: 'ogrenci-firebase.firebaseapp.com',
    storageBucket: 'ogrenci-firebase.firebasestorage.app',
  );
}
